apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: spring-petclinic-1
  labels:
    app.kubernetes.io/part-of: petclinic-server
    apps.kubernetes.io/name: spring-petclinic
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: spring-petclinic-1
spec:
  template:
    metadata:
      annotations:
        boot.spring.io/actuator: http://:8081/actuator
        boot.spring.io/version: 2.4.5
        conventions.apps.tanzu.vmware.com/applied-conventions: |-
          spring-boot-convention/spring-boot
          spring-boot-convention/spring-boot-graceful-shutdown
          spring-boot-convention/spring-boot-web
          spring-boot-convention/spring-boot-actuator
          spring-boot-convention/service-intent-mysql
          appliveview-sample/app-live-view-appflavour-check
          appliveview-sample/app-live-view-connector-boot
          appliveview-sample/app-live-view-appflavours-boot
          appliveview-sample/app-live-view-systemproperties
        developer.conventions/target-containers: workload
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"petclinic-server","apps.kubernetes.io/name":"spring-petclinic","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/workload-type":"web"},"name":"spring-petclinic-1","namespace":"sabari"},"spec":{"env":[{"name":"SPRING_PROFILES_ACTIVE","value":"mysql"},{"name":"JAVA_TOOL_OPTIONS","value":"-Dspring.devtools.restart.enabled=true -Dspring.devtools.restart.poll-interval=2s -Dspring.devtools.restart.quiet-period=1s -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9005\n"}],"params":[{"name":"gitops_repository","value":"ssh://git@github.com/jsabariganesh/tanzu-spring-petclinic.git"},{"name":"gitops_ssh_secret","value":"git-ssh"},{"name":"tekton-pipeline-name","value":"spring-petclinic-tests-pipeline"}],"resources":{"limits":{"cpu":"4000m","memory":"1Gi"},"requests":{"cpu":"100m","memory":"1Gi"}},"serviceClaims":[{"name":"spring-petclinic-db","ref":{"apiVersion":"v1","kind":"Secret","name":"spring-petclinic-db"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/jsabariganesh/spring-petclinic-original"}}}}
        services.conventions.apps.tanzu.vmware.com/mysql: mysql-connector-java/8.0.23
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: petclinic-server
        apps.kubernetes.io/name: spring-petclinic
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: spring-petclinic-1
        conventions.apps.tanzu.vmware.com/framework: spring-boot
        services.conventions.apps.tanzu.vmware.com/mysql: workload
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.actuator.port: "8081"
        tanzu.app.live.view.application.flavours: spring-boot
        tanzu.app.live.view.application.name: spring-petclinic-1
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: mysql
        - name: JAVA_TOOL_OPTIONS
          value: |-
            -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9005
             -Dmanagement.endpoint.health.show-details=always -Dmanagement.endpoints.web.base-path="/actuator" -Dmanagement.endpoints.web.exposure.include=* -Dmanagement.server.port="8081" -Dserver.port="8080" -Dserver.shutdown.grace-period="24s" -Dspring.devtools.restart.enabled="true" -Dspring.devtools.restart.poll-interval="2s" -Dspring.devtools.restart.quiet-period="1s"
        image: jsabariganes.azurecr.io/build/sc/spring-petclinic-1-sabari@sha256:bd257b108e56670e40e4a0ddeb689d6527e8f446e87439d22ed8c3c49483eb4b
        name: workload
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: "4"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 1Gi
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

